name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 22.x
        elixir-version: 1.9.x
    - name: Fetch dependencies
      run: mix deps.get
    - name: Compile the project
      run: mix compile
    - name: Run the tests
      run: mix test
