name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install elixir
      run: apt-get install elixir
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: mix compile
    - name: Run a multi-line script
      run: mix test
